esphome:
  name: talky
  platform: ESP32
  board: lolin32
  on_boot:
    then:
       - delay: 20s
       - uart.write: "\r\nSback to the future!\r\n"

       
substitutions:
 <<: !include ./talky/talky-secrets.yaml
  
#captive_portal:

# Enable logging
#logger:
# hardware_uart: UART1
# level: VERY_VERBOSE
  
ota:
  password: ${ota_pass}

wifi:
  ssid: espota
  password: ${wifi_pass}
  fast_connect: True
  power_save_mode: none
  manual_ip:
    static_ip: 
    gateway: 
    subnet: 
    dns1: 
    dns2: 

#Setup the mqtt bus
mqtt:
  broker: 
  port: 1883
  username: 
  password: ${mqtt_pass}

time:
  - platform: sntp
    id: clocky
    servers: 50.208.57.188
    timezone: America/Los_Angeles

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  id: tts

switch:
  - platform: gpio
    pin: GPIO13
    id: alert_1_emic
    name: "King of the castle"
    on_turn_on:
    - uart.write: "\r\nSWelcome Home Marty, lord of the manor, king of the castle\r\n"
    - delay: 20s
    - switch.turn_off: alert_1_emic
    on_turn_off:
    - uart.write: "\r\nSCLEAR\r\n"
#  - platform: gpio
#    pin: GPIO
#    id: alert_lamp
#    name: "Talky Alert Lamp"
#    on_turn_on:
#    - light.turn_on:
#        id: notify_lamp
#        brightness: 100%
#        red: 100%
#        green: 100%
#        blue: 1.0
#    - delay: 10s
#    - switch.turn_off: alert_lamp
#    on_turn_off:
#    - light.turn_off:
#       id: notify_lamp

#Main Display Code
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2813
    pin: GPIO17
    num_leds: 1
    name: "notify_light"
    id: notify_lamp
    default_transition_length: 0s
    color_correct: [50%, 50%, 50%]
    restore_mode: ALWAYS_OFF